### ISSUE TITLE
Error when using login from web

### ISSUE THREAD

**Issue by jsantamariag** [auth0-blog/flutter-authentication#15]
Hello!
I am developing a multiplarform app in Flutter. I already have my auth0 login working with the base package in mobile, but since that package doesn't support web I'm looking for a package that does. When I tried yours, i get this error when using : Auth0Flutter2.instance.loginUser();

Error: Exception: NoSuchMethodError: tried to call a non-function, such as null: 'dart.global.createAuth0Client'
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/auth0_flutter2/auth0/init_auth0/init_auth0_web.dart 21:5                                                          initAuth0Web
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/auth0_flutter2/auth0/init_auth0/init_auth0_web.dart 5:37                                                          initAuth0Web
packages/auth0_flutter2/auth0/login_user/login_user_web.dart 15:34                                                         loginUser
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/auth0_flutter2/auth0/login_user/login_user_web.dart 8:26                                                          loginUser
packages/auth0_flutter2/auth0/login_user/login_user.dart 13:10                                                             loginUser$
packages/auth0_flutter2/auth0_flutter2.dart 102:25                                                                         loginUser
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/auth0_flutter2/auth0_flutter2.dart 99:28                                                                          loginUser
packages/assistedtourcreator/Tabs/loginTab.dart 203:28                                                                     webLogin
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/assistedtourcreator/Tabs/loginTab.dart 201:11                                                                     webLogin
packages/assistedtourcreator/Tabs/loginTab.dart 412:17                                                                     loginAction
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1660:54                                          runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 767:44                                    handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 796:13                                    _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 567:5                                     [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 874:16                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1660:54                                          runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 767:44                                    handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 796:13                                    _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 567:5                                     [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 640:7                                     callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

Does the package work for web? I hope i didn't do anything wrong. I did this in my initState in main:
/// Also init alternative auth0 package for web/desktop
    Auth0Flutter2.auth0Domain = AUTH0_DOMAIN;
    Auth0Flutter2.auth0ClientId = AUTH0_CLIENT_ID;
    Auth0Flutter2.redirectUri = AUTH0_REDIRECT_URI;
    Auth0Flutter2.setPathUrlStrategy();
    checkForRedirectCallback();

And also added this to web\index.html (hope it's the correct place, the info is not very specific about where to add it exactly) :

  <script src="https://cdn.auth0.com/js/auth0-spa-js/1.13/auth0-spa-js.production.js"></script>

Hope you can help me make it work!

**Comment by jcmartinezdev** [comment]
Hi @jsantamariag,

The [Auth0 SDK for Flutter](https://pub.dev/documentation/auth0_flutter/latest/) currently supports iOS and Android.

There is an [open request](https://github.com/auth0/auth0-flutter/issues/169) to add support for web. I'd recommend that you subscribe to that issue, and add your +1.

If you have any other questions regarding implementation, please let me know :)

**Comment by jsantamariag** [comment]
I found out the error was because the script was added in index.html but in the body part instead of head. If I add it in the head part the login pop up shows, but then the login button does nothing. So i guess that's the common case. I will add my +1 but, will web support be a thing? Are you working on it or do you even plan to do it? Or is it a future (possibly never) plan? Thanks!

Edit: Wait a second, you said the SDK currently supports iOS and Android. Does that mean that there is a restriction that comes from Auth0 and therefore is impossible to implement the auth0 login for web not only in this but any package?

**Comment by jcmartinezdev** [comment]
Hi, yes, some people got it working on different degrees, but so far I haven't seen a successful implementation.

The team has been working on the web support, and even if we don't have a date yet, there has been some progress (you can check out the branches for web development).

I'll ask if we have any updates on it, and if we do, I'll let you know.

Thanks
